name: RoyalIRC
version: ${pluginversion}
main: org.royaldev.royalirc.RoyalIRC
author: jkcclemens
description: Minecraft <-> IRC link
website: http://royaldev.org/
softdepend: [VanishNoPacket]

commands:
  royalirc:
    description: Reloads the plugin.
    aliases: [rirc]
    usage: /<command>
  ircmessage:
    description: Sends a message to a user on IRC.
    aliases: [im]
    usage: /<command> [server] [user] [message]
  irckick:
    description: Kicks a user from a channel on IRC.
    aliases: [ik]
    usage: /<command> [server] [channel] [user] (reason)
  ircrestartbots:
    description: Restarts all IRC bots.
    aliases: [irb]
    usage: /<command>

permissions:
  royalirc.*:
    description: Grants all permissions.
    default: false
    children:
      royalirc.royalirc: true
      royalirc.ircmessage: true
      royalirc.irckick: true
      royalirc.ircrestartbots: true
  royalirc.royalirc:
    description: Allows /royalirc.
    default: op
  royalirc.ircmessage:
    description: Allows /ircmessage.
    default: op
  royalirc.irckick:
    description: Allows /irckick.
    default: op
  royalirc.ircrestartbots:
    description: Allows /ircrestartbots.
    default: op
